[package]
name = "rivenu"
description = "A RISC-V emulator."
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"
readme = "README.md"

[features]

[dependencies]
bytemuck = "1.4.1"
num-traits = "0.2.14"
derive_more = "0.99.11"
